from ui_ux.style import (
    NAV_ITEMS,
    apply_atlas_theme,
    render_app_shell,
    render_feature_card,
    render_info_banner,
    render_metric_card,
    render_page_hero,
    render_section_intro,
    render_sidebar_navigation,
    render_source_card,
    render_topbar,
)
from ui_ux.chart_factory import (
    FONT_FAMILY,
    set_chart_theme,
    create_air_quality_figure,
    create_animated_heatmap,
    create_anomaly_bar_figure,
    create_donut_figure,
    create_forecast_delta_figure,
    create_forecast_figure,
    create_gauge_figure,
    create_globe,
    create_heatmap,
    create_latitude_profile,
    create_live_signal_figure,
    create_prediction_figure,
    create_ranked_bar_figure,
    create_raw_heatmap,
    create_risk_radar,
    create_risk_timeline_figure,
    create_seasonality_bar_figure,
    create_spatial_map,
    create_station_history_figure,
    create_story_bar,
    create_story_comparison,
    create_story_heatmap,
    create_story_scenarios,
    create_story_timeline,
    create_time_series,
    create_timeline_figure,
)

# ── Stitch Design System (additive — new components, old ones untouched) ───
from ui_ux.stitch_tokens import (
    COLORS_DARK,
    COLORS_LIGHT,
    FONT_FAMILIES,
    FONT_SIZES,
    SPACING,
    BORDER_RADIUS,
    SEMANTIC_DARK,
    SEMANTIC_LIGHT,
    NAV_ITEMS_STITCH,
    NAV_ITEMS_SECONDARY,
)
from ui_ux.stitch_effects import (
    STITCH_SCANLINE,
    STITCH_NOISE_TEXTURE,
    STITCH_NEO_BRUTALIST,
    STITCH_LIQUID_HOVER,
    STITCH_LASER_FOCUS,
    STITCH_INNER_GLOW,
    STITCH_STATUS_DOT,
    STITCH_PROGRESS_BAR,
    ALL_STITCH_EFFECTS,
    render_ticker_css,
    render_ticker_bar as render_ticker_bar_html,
    render_progress_bar,
)
from ui_ux.stitch_components import (
    render_bento_card,
    render_anomaly_feed,
    render_signal_card,
    render_alert_card,
    render_hero_analysis,
    render_planetary_gauge,
    render_ticker_bar,
)
